name: Deploy to GitHub Pages

on:
  push:
    paths:
      - '_sources/frontend/vuejs/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: _sources/frontend/vuejs

      - name: Build
        run: npm run build
        working-directory: _sources/frontend/vuejs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _sources/frontend/vuejs/dist/spa